# Generated by Django 4.1.2 on 2022-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rot',
            name='string',
        ),
        migrations.AddField(
            model_name='rot',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество запрсосов'),
        ),
    ]
