# Generated by Django 4.1.2 on 2022-10-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0002_remove_rot_string_rot_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rot',
            options={'ordering': ['-amount'], 'verbose_name': 'Rot', 'verbose_name_plural': 'Rots'},
        ),
    ]
