# Generated by Django 4.1.3 on 2022-11-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0003_alter_rot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rot',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество запрсосов'),
        ),
    ]
