# Generated by Django 4.1.3 on 2022-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rot', models.IntegerField(verbose_name='Сдвиг')),
                ('usages', models.IntegerField(default=1, verbose_name='Количество запрсосов')),
            ],
            options={
                'verbose_name': 'Rot',
                'verbose_name_plural': 'Rots',
                'ordering': ['-usages'],
            },
        ),
    ]
